name: Torrent2GoogleDrive

on:
  workflow_dispatch:
    inputs:
      magnet:
        description: "Magnet Link"
        required: false
        type: string

      torrent_url:
        description: "Torrent File URL"
        required: false
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y aria2 unzip curl jq python3 python3-pip

      - name: Install gdown
        run: |
          pip3 install gdown

      - name: Restore Service Account
        run: |
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT }}' > service-account.json

      - name: Prepare download folder
        run: |
          mkdir downloads

      - name: Download Torrent
        run: |
          if [ ! -z "${{ github.event.inputs.magnet }}" ]; then
            aria2c \
              --seed-time=0 \
              --dir=downloads \
              "${{ github.event.inputs.magnet }}"
          elif [ ! -z "${{ github.event.inputs.torrent_url }}" ]; then
            aria2c \
              --seed-time=0 \
              --dir=downloads \
              "${{ github.event.inputs.torrent_url }}"
          else
            echo "No magnet or torrent URL supplied."
            exit 1
          fi

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [gdrive]
          type = drive
          scope = drive
          service_account_file = service-account.json
          EOF

      - name: Upload to Google Drive
        run: |
          rclone copy downloads gdrive:${{ secrets.GDRIVE_FOLDER_ID }} -P

      - name: Finished
        run: |
          echo "Upload completed."
